name: firedart
description: A dart-native implementation of the Firebase Auth and Firestore SDKs.
version: 0.9.0+1
homepage: https://github.com/cachapa/firedart

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  fixnum: ^1.0.0
  grpc: ^3.0.0
  http: ^0.13.1
  protobuf: ^2.0.0

dev_dependencies:
  coverage: ^1.6.3
  pedantic: ^1.10.0
  test: ^1.16.8
